spring:
  application:
    name: corningrey
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springboot2_db?useSSL=false
      username: root
      password: gEx?N*e)4KrI
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall,log4j2
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  output:
    ansi:
      enabled: detect
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/com/zr/corningrey/**/mysql/*.xml
# Open-feign 配置
feign:
  connectTimeoutMillis: 15000
  readTimeoutMillis: 1800000
rocketmq:
  consumer:
    consumeMessageBatchMaxSize: 1
    consumeThreadMax: 64
    consumeThreadMin: 20
    groupName: ${spring.application.name}
    isOnOff: 'on #该应用是否启用消费者'
    namesrvAddr: localhost:9876
    topics: DemoTopic
  producer:
    groupName: ${spring.application.name}
    isOnOff: 'on #该应用是否启用生产者'
    maxMessageSize: 4096
    namesrvAddr: localhost:9876
    retryTimesWhenSendFailed: 2
    sendMsgTimeout: 3000
server:
  port: 8081
